### ISSUE TITLE
Original Unextracted Data

### ISSUE THREAD

**Issue by dannylin0711** [blead/wf-assets#1]
Sorry, I would like to ask if you have the unextracted data?
I am now working on a memorial site, and find out that I got 1.750.40 version instead of 1.780.40, since the cdn completely closed with access to previous versions, it would miss some of the character and event assets.

**Comment by blead** [comment]
Sorry for the incredibly late reply. Unfortunately I do not.
There are ongoing efforts to archive things in the Discord server and I believe people there do have most of the files saved.
